// Generated by build-support/gen_flags.py. Do not edit.
package com.android.providers.media.flags;

/** aconfig flags of {@code com.android.providers.media.flags}, fixed to their GrapheneOS release values. */
public final class Flags {
    private Flags() {}

    public static final String FLAG_ENABLE_TRASH_AND_RESTORE_BY_FILE_PATH_API = "com.android.providers.media.flags.enable_trash_and_restore_by_file_path_api";

    public static boolean enableTrashAndRestoreByFilePathApi() { return true; }
}
