// Generated by build-support/gen_flags.py. Do not edit.
package com.android.systemui.shared;

/** aconfig flags of {@code com.android.systemui.shared}, fixed to their GrapheneOS release values. */
public final class Flags {
    private Flags() {}

    public static final String FLAG_ENABLE_RECENTS_IN_TASKBAR = "com.android.systemui.shared.enable_recents_in_taskbar";
    public static final String FLAG_WORKSPACE_ITEMS_LABEL_HIDDEN = "com.android.systemui.shared.workspace_items_label_hidden";

    public static boolean enableRecentsInTaskbar() { return false; }
    public static boolean workspaceItemsLabelHidden() { return true; }
}
