#!/usr/bin/env python3
# Copyright (C) 2026 The Folio Authors
# SPDX-License-Identifier: Apache-2.0
"""Generates the aconfig feature-flag classes Folio needs, without Soong.

Soong generates a Java class per aconfig package from flag declarations and the
release config's flag values. This script does the same for a Gradle build:

* com.android.launcher3.Flags: every flag declared in launcher3/aconfig/*.aconfig.
* Flags classes of other packages (SystemUI, WM Shell, MediaProvider): only the
  flags the vendored sources actually call.
* Framework packages (android.*, com.android.window.flags) are generated under
  com.android.launcher3.folio.platformflags instead, because a class with the
  framework's name would be shadowed at runtime by the hidden framework copy.

Values come from a snapshot of GrapheneOS build/release (see flag_values.txt),
resolved for the "cur" release config used by GrapheneOS user builds.

Usage:
  gen_flags.py resolve <platform_build_release checkout>   # refresh flag_values.txt
  gen_flags.py generate <output dir>                        # write the Java classes
"""
import collections
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HERE = os.path.dirname(os.path.abspath(__file__))
VALUES_FILE = os.path.join(HERE, "flag_values.txt")
SRC_ROOTS = ["launcher3", "systemui", "frameworks"]
LAUNCHER_PKG = "com.android.launcher3"
RELOCATE_PREFIX = "com.android.launcher3.folio.platformflags"
# Framework (boot classpath) flag packages and the class each is relocated to.
RELOCATED = {
    "android.security": "AndroidSecurityFlags",
    "android.multiuser": "AndroidMultiuserFlags",
    "android.appwidget.flags": "AndroidAppwidgetFlags",
    "android.os": "AndroidOsFlags",
    "com.android.window.flags": "WindowFlags",
}
RELEASE_CONFIG = "cur"
BUILD_VARIANT = "user"


# ---------------------------------------------------------------- resolve

def _parse_release_configs(brel):
    configs = {}
    aliases = {}
    cdir = os.path.join(brel, "release_configs")
    for f in os.listdir(cdir):
        if not f.endswith(".textproto"):
            continue
        text = open(os.path.join(cdir, f)).read()
        name = re.search(r'^name:\s*"([^"]+)"', text, re.M).group(1)
        configs[name] = re.findall(r'^inherits:\s*"([^"]+)"', text, re.M)
    mp = os.path.join(brel, "release_config_map.textproto")
    for m in re.finditer(r'aliases:\s*{\s*name:\s*"([^"]+)"\s*target:\s*"([^"]+)"', open(mp).read()):
        aliases[m.group(1)] = m.group(2)
    return configs, aliases


def _config_order(name, configs, aliases, seen):
    name = aliases.get(name, name)
    if name in seen:
        return []
    seen.add(name)
    order = []
    for parent in configs.get(name, []):
        order += _config_order(parent, configs, aliases, seen)
    order.append(name)
    return order


def resolve(brel):
    configs, aliases = _parse_release_configs(brel)
    order = _config_order(RELEASE_CONFIG, configs, aliases, set()) + [BUILD_VARIANT]
    values = {}
    for cfg in order:
        d = os.path.join(brel, "aconfig", cfg)
        if not os.path.isdir(d):
            continue
        for root, _, files in os.walk(d):
            for f in sorted(files):
                if not f.endswith(".textproto"):
                    continue
                text = open(os.path.join(root, f)).read()
                for block in re.findall(r"flag_value\s*{([^}]*)}", text):
                    pkg = re.search(r'package:\s*"([^"]+)"', block)
                    nm = re.search(r'name:\s*"([^"]+)"', block)
                    st = re.search(r"state:\s*(\w+)", block)
                    if pkg and nm and st:
                        values[pkg.group(1) + "." + nm.group(1)] = st.group(1) == "ENABLED"
    # Keep only the packages Folio uses, so the snapshot stays small and reviewable.
    wanted = {LAUNCHER_PKG} | set(referenced_flags())
    values = {k: v for k, v in values.items() if k.rsplit(".", 1)[0] in wanted}
    with open(VALUES_FILE, "w") as out:
        out.write("# Resolved aconfig flag values for GrapheneOS release config '%s' (%s).\n"
                  % (RELEASE_CONFIG, " -> ".join(order)))
        out.write("# Generated by gen_flags.py resolve; flags not listed are disabled.\n")
        for key in sorted(values):
            out.write("%s=%s\n" % (key, "true" if values[key] else "false"))
    print("wrote %d values from %s" % (len(values), " -> ".join(order)))


# ---------------------------------------------------------------- generate

def _load_values():
    values = {}
    for line in open(VALUES_FILE):
        line = line.strip()
        if line and not line.startswith("#"):
            k, v = line.split("=")
            values[k] = v == "true"
    return values


def _launcher_flags():
    names = []
    for f in sorted(os.listdir(os.path.join(ROOT, "launcher3", "aconfig"))):
        if f.endswith(".aconfig"):
            text = open(os.path.join(ROOT, "launcher3", "aconfig", f)).read()
            assert re.search(r'^package:\s*"%s"' % re.escape(LAUNCHER_PKG), text, re.M), f
            names += re.findall(r'flag\s*{\s*name:\s*"([^"]+)"', text)
    return names


def _source_files():
    for top in SRC_ROOTS:
        for root, _, files in os.walk(os.path.join(ROOT, top)):
            for f in files:
                if f.endswith((".java", ".kt")):
                    yield os.path.join(root, f)


def referenced_flags():
    """Returns {flags package: set(method names)} for packages other than the launcher's."""
    refs = collections.defaultdict(set)
    for path in _source_files():
        text = open(path, errors="ignore").read()
        # FQN calls: com.example.Flags.someFlag
        for pkg, name in re.findall(r"\b((?:[a-z][a-z0-9_]*\.)+[a-z0-9_]+)\.Flags\.([a-zA-Z_][a-zA-Z0-9_]*)", text):
            refs[pkg].add(name)
        # Static/Kotlin member imports: import [static] com.example.Flags.someFlag
        for pkg, name in re.findall(r"^import\s+(?:static\s+)?([\w.]+)\.Flags\.(\w+)", text, re.M):
            refs[pkg].add(name)
        # Class imports: import com.example.Flags; then Flags.someFlag
        for pkg in re.findall(r"^import\s+([\w.]+)\.Flags;?\s*$", text, re.M):
            for name in re.findall(r"(?<![\w.])Flags\.([a-zA-Z_]\w*)", text):
                refs[pkg].add(name)
        # References already rewritten by relocate_flags.py to the bundled framework copies.
        for pkg, cls in RELOCATED.items():
            fq = re.escape(RELOCATE_PREFIX + "." + cls)
            for name in re.findall(r"%s\.([a-zA-Z_]\w*)" % fq, text):
                refs[pkg].add(name)
            if re.search(r"^import\s+%s;?\s*$" % fq, text, re.M):
                for name in re.findall(r"(?<![\w.])%s\.([a-zA-Z_]\w*)" % re.escape(cls), text):
                    refs[pkg].add(name)
    refs.pop(LAUNCHER_PKG, None)
    for pkg in list(refs):
        refs[pkg] = {n for n in refs[pkg] if not n.startswith("FLAG_") and n != "class"}
    return refs


def _camel(name):
    parts = name.split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def _snake(camel, pkg, values):
    """Maps a generated method name back to its aconfig flag name, using the known values."""
    for key in values:
        p, name = key.rsplit(".", 1)
        if p == pkg and _camel(name) == camel:
            return name
    return re.sub(r"(?<!^)(?=[A-Z])", "_", camel).lower()


def _write_class(out_dir, pkg, cls, flags, values, flag_pkg):
    """flags: list of aconfig flag names (snake_case)."""
    lines = [
        "// Generated by build-support/gen_flags.py. Do not edit.",
        "package %s;" % pkg,
        "",
        "/** aconfig flags of {@code %s}, fixed to their GrapheneOS release values. */" % flag_pkg,
        "public final class %s {" % cls,
        "    private %s() {}" % cls,
        "",
    ]
    for f in sorted(set(flags)):
        lines.append('    public static final String FLAG_%s = "%s.%s";' % (f.upper(), flag_pkg, f))
    lines.append("")
    for f in sorted(set(flags)):
        v = values.get(flag_pkg + "." + f, False)
        lines.append("    public static boolean %s() { return %s; }" % (_camel(f), "true" if v else "false"))
    lines.append("}")
    d = os.path.join(out_dir, *pkg.split("."))
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, cls + ".java"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return sum(1 for f in set(flags) if values.get(flag_pkg + "." + f, False))


def generate(out_dir):
    values = _load_values()
    on = _write_class(out_dir, LAUNCHER_PKG, "Flags", _launcher_flags(), values, LAUNCHER_PKG)
    print("%s.Flags: %d flags, %d enabled" % (LAUNCHER_PKG, len(_launcher_flags()), on))
    for pkg, names in sorted(referenced_flags().items()):
        flags = [_snake(n, pkg, values) for n in names]
        if pkg in RELOCATED:
            _write_class(out_dir, RELOCATE_PREFIX, RELOCATED[pkg], flags, values, pkg)
            target = RELOCATE_PREFIX + "." + RELOCATED[pkg]
        else:
            _write_class(out_dir, pkg, "Flags", flags, values, pkg)
            target = pkg + ".Flags"
        print("%s <- %s: %s" % (target, pkg, ", ".join(
            "%s=%s" % (n, values.get(pkg + "." + _snake(n, pkg, values), False))
            for n in sorted(names))))


if __name__ == "__main__":
    if len(sys.argv) != 3 or sys.argv[1] not in ("resolve", "generate"):
        sys.exit(__doc__)
    resolve(sys.argv[2]) if sys.argv[1] == "resolve" else generate(sys.argv[2])
