// Generated by build-support/gen_flags.py. Do not edit.
package com.android.wm.shell;

/** aconfig flags of {@code com.android.wm.shell}, fixed to their GrapheneOS release values. */
public final class Flags {
    private Flags() {}

    public static final String FLAG_ENABLE2X1_SPLIT = "com.android.wm.shell.enable2x1_split";
    public static final String FLAG_ENABLE_BUBBLE_ANYTHING = "com.android.wm.shell.enable_bubble_anything";
    public static final String FLAG_ENABLE_BUBBLE_BAR = "com.android.wm.shell.enable_bubble_bar";
    public static final String FLAG_ENABLE_BUBBLE_BAR_ON_PHONES = "com.android.wm.shell.enable_bubble_bar_on_phones";
    public static final String FLAG_ENABLE_BUBBLE_TO_FULLSCREEN = "com.android.wm.shell.enable_bubble_to_fullscreen";
    public static final String FLAG_ENABLE_BUBBLE_TRANSITION_PLANNER = "com.android.wm.shell.enable_bubble_transition_planner";
    public static final String FLAG_ENABLE_CREATE_ANY_BUBBLE = "com.android.wm.shell.enable_create_any_bubble";
    public static final String FLAG_ENABLE_GSF = "com.android.wm.shell.enable_gsf";
    public static final String FLAG_ENABLE_TINY_TASKBAR = "com.android.wm.shell.enable_tiny_taskbar";

    public static boolean enable2x1Split() { return false; }
    public static boolean enableBubbleAnything() { return false; }
    public static boolean enableBubbleBar() { return true; }
    public static boolean enableBubbleBarOnPhones() { return false; }
    public static boolean enableBubbleToFullscreen() { return false; }
    public static boolean enableBubbleTransitionPlanner() { return false; }
    public static boolean enableCreateAnyBubble() { return true; }
    public static boolean enableGsf() { return true; }
    public static boolean enableTinyTaskbar() { return false; }
}
