// Generated by build-support/gen_flags.py. Do not edit.
package com.android.launcher3.folio.platformflags;

/** aconfig flags of {@code android.multiuser}, fixed to their GrapheneOS release values. */
public final class AndroidMultiuserFlags {
    private AndroidMultiuserFlags() {}

    public static final String FLAG_ENABLE_MOVING_CONTENT_INTO_PRIVATE_SPACE = "android.multiuser.enable_moving_content_into_private_space";

    public static boolean enableMovingContentIntoPrivateSpace() { return true; }
}
