// Generated by build-support/gen_flags.py. Do not edit.
package com.android.launcher3.folio.platformflags;

/** aconfig flags of {@code android.security}, fixed to their GrapheneOS release values. */
public final class AndroidSecurityFlags {
    private AndroidSecurityFlags() {}

    public static final String FLAG_APP_LOCK_APIS = "android.security.app_lock_apis";

    public static boolean appLockApis() { return false; }
}
