// Generated by build-support/gen_flags.py. Do not edit.
package com.android.launcher3.folio.platformflags;

/** aconfig flags of {@code android.appwidget.flags}, fixed to their GrapheneOS release values. */
public final class AndroidAppwidgetFlags {
    private AndroidAppwidgetFlags() {}

    public static final String FLAG_GENERATED_PREVIEWS = "android.appwidget.flags.generated_previews";

    public static boolean generatedPreviews() { return true; }
}
