// Generated by build-support/gen_flags.py. Do not edit.
package com.android.launcher3.folio.platformflags;

/** aconfig flags of {@code com.android.window.flags}, fixed to their GrapheneOS release values. */
public final class WindowFlags {
    private WindowFlags() {}

    public static final String FLAG_ENABLE_BUBBLE_ROOT_TASK = "com.android.window.flags.enable_bubble_root_task";
    public static final String FLAG_ENABLE_NON_DEFAULT_DISPLAY_SPLIT_BUGFIX = "com.android.window.flags.enable_non_default_display_split_bugfix";
    public static final String FLAG_SHOW_HOME_BEHIND_DESKTOP = "com.android.window.flags.show_home_behind_desktop";
    public static final String FLAG_TRANSIT_MIXPATCHER_BASE = "com.android.window.flags.transit_mixpatcher_base";

    public static boolean enableBubbleRootTask() { return true; }
    public static boolean enableNonDefaultDisplaySplitBugfix() { return true; }
    public static boolean showHomeBehindDesktop() { return false; }
    public static boolean transitMixpatcherBase() { return false; }
}
